name: checks
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .php$ | xargs)"

#      - name: list files
#        run: |
#          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
#          CHANGED_FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename ' | grep '.php')
#          echo $CHANGED_FILES >> $GITHUB_ENV

#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
#          tools: composer:v2
#          coverage: none

#      - name: Install dependencies
#        run: composer install --no-interaction --no-progress

#      - name: PHP Unit Test 
#        run: CI/PHPUnit/run_tests.sh

#      - name: Install PHP CS Fixer
#        run: composer require friendsofphp/php-cs-fixer --no-interaction --no-progress

#      - name: PHP CS Fixer
#        run: CI/PHP-CS-Fixer/run_check.sh

#      - name: Special Char Checker
#        run: CI/Special-Char-Checker/special-char-checker.sh
